// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqeeaFJMnrQL6W2TW34GJhZmz2q8Mn74k',
    appId: '1:28883576570:android:012205105463de7c3b4b43',
    messagingSenderId: '28883576570',
    projectId: 'shop-e2be0',
    storageBucket: 'shop-e2be0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRNQ0kWMcsh18YtRvbInkwTpTfN5bz7k',
    appId: '1:28883576570:ios:9a0958088805e3053b4b43',
    messagingSenderId: '28883576570',
    projectId: 'shop-e2be0',
    storageBucket: 'shop-e2be0.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaRNQ0kWMcsh18YtRvbInkwTpTfN5bz7k',
    appId: '1:28883576570:ios:9a0958088805e3053b4b43',
    messagingSenderId: '28883576570',
    projectId: 'shop-e2be0',
    storageBucket: 'shop-e2be0.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDgHhJP3zyRuIMb7oXo8vcC1i_vHlGEE',
    appId: '1:28883576570:web:9a2cd48d0f6d348b3b4b43',
    messagingSenderId: '28883576570',
    projectId: 'shop-e2be0',
    authDomain: 'shop-e2be0.firebaseapp.com',
    storageBucket: 'shop-e2be0.appspot.com',
    measurementId: 'G-D50TCL1MG6',
  );
}
